Reinstall webpack to mitigate security issue with serialize-javascript
capraconsulting/redcross-digital-leksehjelp-frontend-student pull request #87
Opened 2019-12-10 15:34 UTC by scbasma

La til ^ for å oppdatere webpack dependencies til siste minor/patch versjon. 

Gjerne ta en vurdering her på om vi ønsker at ^ skal legges til. I utgangspunktet skal det ikke ha så mye å si, ettersom det i teorien ikke skal introdusere breaking changes.

2019-12-10 16:25 UTC, thrap approved these changes

2019-12-10 17:26 UTC, henrist requested changes
Det er foretrukket at dependencies er pinnet til en fast versjon i `package.json`. Gjeldende Renovate-oppsett vil automatisk pinne denne avhengigheten når dette merges (og litt usikker om den da ruller tilbake).

https://github.com/capraconsulting/redcross-digital-leksehjelp-frontend-student/blob/bec857c4d0d7e70a1ef0c8e37587509355e932d4/renovate.json#L11-L13

Se forøvrig https://docs.renovatebot.com/dependency-pinning/#so-whats-best (og hele dokumentet hvis du virkelig vil gå i dybden)

2019-12-10 17:33 UTC, henrist commented
Merk forvørig at det du egentlig ønsker å gjøre her er ikke å reinstallere webpack, men å oppfriske lockfile. Se https://confluence.capraconsulting.no/display/CALS/Keeping+dependencies+up-to-date#Keepingdependenciesup-to-date-Lockfilemanagementandtransitivedependencies

Egentlig lurer jeg litt på hvorfor renovate ikke har oppdatert denne selv. Det pleier å skje natt til mandager.

2019-12-11 09:05 UTC, scbasma commented
Takk for grundig tilbakemelding @henrist! Gikk tilbake til pinned dependency handling i 12ebfb8

2019-12-11 09:13 UTC, henrist approved these changes
I utgangspunktet ville jeg tenkt det hadde vært enklest å oppdatere hele lockfilen, men dette gjør jobben for dette spesifikke use-caset.

Jeg aktiverte nettopp Renovate "master issue" i cc4839f11. Dette gjør at Renovate har opprettet #90. Jeg hadde egentlig forventet at jeg kunne huke av "Lock file maintenance" i denne, men det ser kun ut som den [oppretter branchen](https://github.com/capraconsulting/redcross-digital-leksehjelp-frontend-student/tree/renovate/lock-file-maintenance) og ikke PR-en for oppgaven.

2019-12-11 09:21 UTC, scbasma commented
Jeg fulgte prosedyre for oppdatering av transitive dependencies, altså slette lock-file og så kjøre en npm install. Ingen endringer ble generert i lock-filen lokalt ihvertfall. Er dette rar oppførsel? Ser at "Lock file maintenance" gjennom renovate generer en hel del endringer.

2019-12-11 09:36 UTC, henrist commented
```bash
git checkout LEKSE-235-update-serialize-javascript-dependency
git pull
rm package-lock.json
npm install
```

Får en masse andre endringer her i hvert fall. Men du gjorde kanskje ikke dette på nytt i dag?

2019-12-11 10:01 UTC, scbasma commented
Jeg prøvde dette idag! Hmm, så rart.

2019-12-11 14:25 UTC, henrist commented
Men uansett, er vel bare å merge dette og bli ferdig med det. Så oppretter Renovate en egen oppdatering for de andre tingene senere.

2020-01-28 07:41 UTC, henrist commented
This has already been resolved by lock file update

2020-01-28 07:41 UTC, closed without merging